In [4]:
#Q1
def three_number_summary(a_list):
    print('max=',max(a_list),'min=',min(a_list),'average=',sum(a_list)/len(a_list))
    return


In [2]:
three_number_summary([1,2,3,4,5])

5 1 3.0


In [1]:
three_number_summary([1,2,3,4,7,8,9])

NameError: name 'three_number_summary' is not defined

In [12]:
#Q2
#number
num=12
num1=num
num1+=1
a=(num1==num)
print('number mutability',a)
#string
word='computational'
word1=word
word1+='a'
b=(word1==word)
print('string mutability',b)
#list
l=[1,2,3,4]
l1=l
l1.append(1)
print('list mutability',l==l1)
#tuples
tup=(1,2,3,4)
tup1=tup
tup1+=(1,)
print('tuple mutability',tup==tup1)
#dictionary
dict1={'type':'rpg','brand':'type-moon'}
dict2=dict1
dict2[type]='a'
print('dictionary mutability',dict1==dict2)


False
False
True
False
True


In [1]:
#Q3
import calculator as cal

In [2]:
#Let's assume there is a right triangle whose legs are 3cm and 4 cm, use calculaor module to solve for the hypotenuse
h=cal.sqrt(cal.pro(3,3)+cal.pro(4,4))
print('the hypotunse is ', h)

In [3]:
h

5.0

In [7]:
import numpy as np
#numpy part Q1
A=np.array([[3,-1,4],[1,5,-9]])
B=np.array([[2,6,-5,3],[5,-8,9,7],[9,-3,-2,-3]])
C=np.dot(A,B)
print(C)

[[ 37  14 -32 -10]
 [-54  -7  58  65]]


In [8]:
#Q2
def calculation(x,y,z):
    A=np.array([x,y,z])
    C=-np.dot(A,np.dot(A,A))+9*np.dot(A,A)-15*A
    return C

In [9]:
x=[3,1,4]
y=[1,5,9]
z=[-5,3,1]
calculation(x,y,z)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [40]:
#Q5
A=np.array([[0,2,4],[1,3,5]])
B=np.transpose(np.triu(np.ones(3)*3,0))
C=np.diag([-2,-2,-2])

In [58]:
answer=np.vstack([np.hstack([np.zeros([3,3]),np.transpose(A),np.identity(3)]),np.hstack([A,np.zeros([2,5])]),
                           np.hstack([B,np.zeros([3,2]),C])])


In [59]:
answer

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2.,  0.,  0.],
       [ 3.,  3.,  0.,  0.,  0.,  0., -2.,  0.],
       [ 3.,  3.,  3.,  0.,  0.,  0.,  0., -2.]])

In [1]:
#OOP
#Q1
class Backpack(object):
    def __init__(self,name,color,max_size=5):
        self.name=name
        self.color=color
        self.max_size=max_size
        self.contents=[]
        
    def put(self,item):
        self.contents.append(item)
        if len(self.contents)>5:
            self.contents.remove(item)
            print('No Room!')
            
    def dump(self):
        del self.contents[:]
      

In [2]:
def test_backpack():
    testpack = Backpack("Barry", "black") 
    if testpack.max_size != 5:
        print("Wrong default max_size!")
    for item in ["pencil", "pen", "paper", "computer"]:
        testpack.put(item) 
    print(testpack.contents)

In [3]:
test_backpack()


['pencil', 'pen', 'paper', 'computer']


In [4]:
#Q2

      

      

In [8]:
class Jetpack(Backpack):
    def __init__(self,name,color,max_size=2):
        Backpack.__init__(self,name,color,max_size)
        self.fuel=10
    def fly(self,burned_fuel):
        if burned_fuel>self.fuel:
                print('Not Enough Fuel')
        else:
                self.fuel=self.fuel-burned_fuel

        
      
    
                
        def dump(self):
            Backpack.dump(self)
            self.fuel=0                
        




In [9]:
a=Jetpack('aaa','asdqw')

In [10]:
a.fly(12)

Not Enough Fuel
